version: '3.8'

# To run: `docker-compose -f docker-compose.yml -f docker-compose.staging.yml up -d`

services:
  backend:
    build:
      target: production
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=debug # Might want more logs in staging
    restart: unless-stopped

  frontend:
    build:
      target: production
    restart: unless-stopped

  db:
    # Staging might use a smaller database or specific init scripts
    restart: unless-stopped
